name: InfuseSMP
version: '1.0.0'
main: com.infuse.InfusePlugin
api-version: '1.21'
author: domc888
commands:
  infuse:
    usage: /infuse <give|clear|cooldown|reload>
  lspark:
    usage: /lspark
  rspark:
    usage: /rspark
  ldrain:
    usage: /ldrain
  rdrain:
    usage: /rdrain
  swap:
    usage: /swap
  controls:
    usage: /controls
  cleareffects:
    usage: /cleareffects <player>
  cooldown:
    usage: /cooldown <player>
permissions:
  infuse.use:
    default: true
  infuse.admin:
    default: op